# Generated by Django 5.2.4 on 2026-08-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FdsStudentFeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('OVERDUE', 'Overdue'), ('SETTLED', 'Settled')], default='ACTIVE', max_length=20)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fds.fdsfeestructure')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_account', to='fds.fdsstudent')),
            ],
            options={
                'verbose_name': 'FDS Student Fee Account',
                'ordering': ['-updated_at'],
            },
        ),
    ]
