# Generated by Django 5.2.4 on 2026-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0002_fdsstudentfeeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdsfeescollection',
            name='mode_of_pay',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('ONLINE', 'Online'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
    ]
