# Generated by Django 5.2.4 on 2026-09-09 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0002_fdsstudentfeeaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FdsLeadSourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('COLLEGES', 'Prominent Colleges in & around Kottayam'), ('SCHOOLS', 'Prominent Schools in & around Kottayam'), ('CLUBS', 'Recreation & Social Clubs in Kottayam'), ('RESIDENTS', 'Resident Welfare Associations & Housing Hubs (Proper Kottayam)'), ('VILLAS', 'Prominent Villa Projects & Gated Communities in Kottayam'), ('BUILDERS', 'Residency / Builder')], default='COLLEGES', max_length=50)),
                ('name', models.CharField(help_text='Institution / School / Club / Association / Villa / Builder Name', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Location / Area / Landmark', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone Number / Contact Number', max_length=200, null=True)),
                ('email_website', models.CharField(blank=True, help_text='Email / Website', max_length=255, null=True)),
                ('extra_info', models.CharField(blank=True, help_text='Board/Type for schools, Contact/Remarks for associations', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FDS Lead Sourcing',
                'verbose_name_plural': 'FDS Lead Sourcing Entries',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='fdsfeestructure',
            options={'ordering': ['id'], 'verbose_name': 'FDS Fee Structure'},
        ),
        migrations.AddField(
            model_name='fdsenquiry',
            name='joined_status',
            field=models.CharField(blank=True, help_text='Joined Or Not (Joined, None)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdsenquiry',
            name='parent_name',
            field=models.CharField(blank=True, help_text='Parent Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fdsenquiry',
            name='previous_exp',
            field=models.CharField(blank=True, help_text='Previous Exp. (1year, yes,4yrs, etc.)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fdsfeescollection',
            name='batch_time_text',
            field=models.CharField(blank=True, help_text='Batch/Time from sheet', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fdsfeescollection',
            name='fees_type_text',
            field=models.CharField(blank=True, default='MONTHLY', help_text='Fees Type e.g. MONTHLY', max_length=100),
        ),
        migrations.AddField(
            model_name='fdsfeescollection',
            name='month_name',
            field=models.CharField(blank=True, help_text='Month from sheet e.g. SEPTEMBER', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdsfeescollection',
            name='paid_amount_text',
            field=models.CharField(blank=True, help_text='Paid Amount text e.g. 1600/-', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdsfeescollection',
            name='status_remarks',
            field=models.CharField(blank=True, help_text='Status/Remarks e.g. OFFER PRICE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fdsfeescollection',
            name='student_id_code',
            field=models.CharField(blank=True, help_text='Student ID e.g. FDSKTM001', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdsfeescollection',
            name='student_name_text',
            field=models.CharField(blank=True, help_text='Student Name from sheet', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fdsfeescollection',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='TRANSACTION ID e.g. 110622717946', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fdsfeestructure',
            name='amount_text',
            field=models.CharField(blank=True, help_text='e.g. 12,000 / 8,000 or 1600', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fdsfeestructure',
            name='category_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fdsstudent',
            name='age_gender',
            field=models.CharField(blank=True, help_text='Age & Gender e.g. 5/F, 27/F, 6,F', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdsstudent',
            name='batch_time_text',
            field=models.CharField(blank=True, help_text='Batch/Time e.g. SUN,SAT ,11-12pm', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fdsstudent',
            name='fee_paid_date',
            field=models.DateField(blank=True, help_text='Admission Fee /Monthly fee Paid Date', null=True),
        ),
        migrations.AddField(
            model_name='fdstrial',
            name='converted_text',
            field=models.CharField(blank=True, help_text='Converted text e.g. JOINED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdstrial',
            name='fee_status',
            field=models.CharField(blank=True, default='PENDING', help_text='Fee e.g. PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='fdstrial',
            name='time_text',
            field=models.CharField(blank=True, help_text='Time text e.g. 16:30, 18:00', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fdsenquiry',
            name='age',
            field=models.CharField(blank=True, help_text='Age (e.g. 5yrs, College student, 30yrs)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fdsenquiry',
            name='class_interest',
            field=models.CharField(blank=True, default='DANCE', max_length=50),
        ),
        migrations.AlterField(
            model_name='fdsenquiry',
            name='enquiry_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fdsenquiry',
            name='name',
            field=models.CharField(help_text='Student Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='fdsenquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fdsenquiry',
            name='preferred_timing',
            field=models.CharField(blank=True, help_text='Preferred Timing', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fdsenquiry',
            name='remarks',
            field=models.TextField(blank=True, help_text='Remarks / Concerns', null=True),
        ),
        migrations.AlterField(
            model_name='fdsenquiry',
            name='source',
            field=models.CharField(blank=True, default='WALK_IN', help_text='Source (INSTAGRAM, Facebook ad, etc.)', max_length=150),
        ),
        migrations.AlterField(
            model_name='fdsenquiry',
            name='status',
            field=models.CharField(blank=True, default='interested', max_length=100),
        ),
        migrations.AlterField(
            model_name='fdsenquiry',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fdsfeescollection',
            name='fee_year',
            field=models.PositiveIntegerField(blank=True, default=2026, null=True),
        ),
        migrations.AlterField(
            model_name='fdsfeescollection',
            name='fees_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='fds.fdsfeestructure'),
        ),
        migrations.AlterField(
            model_name='fdsfeescollection',
            name='mode_of_pay',
            field=models.CharField(blank=True, default='ONLINE', help_text='Mode Of Pay e.g. ONLINE, CASH', max_length=50),
        ),
        migrations.AlterField(
            model_name='fdsfeescollection',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fdsfeescollection',
            name='pay_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='fdsfeescollection',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fdsfeescollection',
            name='status',
            field=models.CharField(blank=True, default='PAID', max_length=50),
        ),
        migrations.AlterField(
            model_name='fdsfeescollection',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fdsfeestructure',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fdsstudent',
            name='can_leave_alone',
            field=models.CharField(blank=True, default='NO', help_text='Can Leave alone e.g. NO, YES', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fdsstudent',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fdsstudent',
            name='emergency_contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fdsstudent',
            name='medical_condition',
            field=models.CharField(blank=True, default='NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fdsstudent',
            name='pickup_person_1_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fdsstudent',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fdsstudent',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fdstrial',
            name='age',
            field=models.CharField(blank=True, help_text='Age e.g. 5, 6, 5 3/4', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fdstrial',
            name='class_category',
            field=models.CharField(blank=True, default='DANCE', max_length=50),
        ),
        migrations.AlterField(
            model_name='fdstrial',
            name='fee_quoted',
            field=models.CharField(blank=True, default='', help_text='Fee quoted e.g. 1600/-', max_length=50),
        ),
        migrations.AlterField(
            model_name='fdstrial',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback e.g. SATISFYING,EXCELLENT', null=True),
        ),
        migrations.AlterField(
            model_name='fdstrial',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Follow up date', null=True),
        ),
        migrations.AlterField(
            model_name='fdstrial',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fdstrial',
            name='remarks',
            field=models.TextField(blank=True, help_text='Remarks e.g. SAT,SUN ,11-12PM', null=True),
        ),
        migrations.AlterField(
            model_name='fdstrial',
            name='status',
            field=models.CharField(blank=True, default='WILL INFORM', max_length=100),
        ),
        migrations.AlterField(
            model_name='fdstrial',
            name='trainer_rating',
            field=models.CharField(blank=True, help_text='Rating out of 5', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fdstrial',
            name='trial_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
