# Generated by Django 5.2.4 on 2026-09-21 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0003_alter_fdsfeescollection_mode_of_pay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fdsfeescollection',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='fds.fdsstudentfeeaccount'),
        ),
        migrations.AddField(
            model_name='fdsstudentfeeaccount',
            name='due_day',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='fdsstudentfeeaccount',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fdsstudentfeeaccount',
            name='next_due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fdsstudentfeeaccount',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fdsstudentfeeaccount',
            name='overdue_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fdsstudentfeeaccount',
            name='plan_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='fdsstudentfeeaccount',
            name='plan_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='fdsstudentfeeaccount',
            name='plan_type',
            field=models.CharField(choices=[('ONE_TIME', 'One Time'), ('INSTALLMENT', 'Installment'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom'), ('PACKAGE', 'Package')], default='PACKAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='fdsstudentfeeaccount',
            name='registration_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fdsstudentfeeaccount',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fdsstudentfeeaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('OVERDUE', 'Overdue'), ('SETTLED', 'Settled'), ('RESTRUCTURED', 'Restructured'), ('WAIVED', 'Waived')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='FdsFeeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('WAIVER', 'Waiver'), ('REFUND', 'Refund'), ('RESTRUCTURE', 'Restructure'), ('CONCESSION', 'Concession'), ('MANUAL', 'Manual')], max_length=20)),
                ('amount_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='fds.fdsstudentfeeaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fds_fee_adjustments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FdsFeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('due_date', models.DateField(db_index=True)),
                ('scheduled_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fds.fdsstudentfeeaccount')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('account', 'sequence_number')},
            },
        ),
        migrations.AddField(
            model_name='fdsfeescollection',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='fds.fdsfeeinstallment'),
        ),
    ]
