# Generated by Django 5.2.4 on 2026-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0004_fdsfeescollection_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fdsfeestructure',
            options={'ordering': ['category', 'name'], 'verbose_name': 'FDS Fee Structure'},
        ),
        migrations.AddField(
            model_name='fdsfeestructure',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fdsfeestructure',
            name='batch_type',
            field=models.CharField(blank=True, default='WEEKEND', max_length=50),
        ),
        migrations.AddField(
            model_name='fdsfeestructure',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fdsfeestructure',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='fdsfeestructure',
            name='sessions_per_week',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='fdsfeestructure',
            name='category',
            field=models.CharField(default='DANCE', max_length=50),
        ),
    ]
