# Generated by Django 5.2.4 on 2026-09-24 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0005_alter_fdsfeestructure_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fdsbatch',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fds_batches_coordinated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fdsweddinggroup',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fds_wedding_groups_coordinated', to=settings.AUTH_USER_MODEL),
        ),
    ]
