# Generated by Django 5.2.4 on 2026-09-24 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0006_fdsbatch_coordinator_fdsweddinggroup_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdsfeescollection',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fds.fdsstudentfeeaccount'),
        ),
    ]
