# Generated by Django 5.2.4 on 2026-09-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0007_alter_fdsfeescollection_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdsbatch',
            name='branch',
            field=models.CharField(choices=[('KOTTAYAM', 'Kottayam'), ('KOCHI', 'Kochi')], default='KOTTAYAM', max_length=20),
        ),
        migrations.AddField(
            model_name='fdsenquiry',
            name='branch',
            field=models.CharField(choices=[('KOTTAYAM', 'Kottayam'), ('KOCHI', 'Kochi')], default='KOTTAYAM', max_length=20),
        ),
        migrations.AddField(
            model_name='fdsstudent',
            name='branch',
            field=models.CharField(choices=[('KOTTAYAM', 'Kottayam'), ('KOCHI', 'Kochi')], default='KOTTAYAM', max_length=20),
        ),
        migrations.AddField(
            model_name='fdstrial',
            name='branch',
            field=models.CharField(choices=[('KOTTAYAM', 'Kottayam'), ('KOCHI', 'Kochi')], default='KOTTAYAM', max_length=20),
        ),
        migrations.AddField(
            model_name='fdsweddinggroup',
            name='branch',
            field=models.CharField(choices=[('KOTTAYAM', 'Kottayam'), ('KOCHI', 'Kochi')], default='KOTTAYAM', max_length=20),
        ),
    ]
