# Generated by Django 5.2.4 on 2026-10-03 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0009_fdstasktemplate_fdsweeklytask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdstasktemplate',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fds_task_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
