# Generated by Django 5.2.4 on 2026-10-08 10:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('VOXBAY', 'Voxbay'), ('META', 'Meta Ads')], max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('follow_up_date', models.DateField()),
                ('follow_up_time', models.TimeField(blank=True, null=True)),
                ('followup_type', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('meeting', 'Meeting')], default='call', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('not_interested', 'Not Interested'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('converted_to_lead', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to=settings.AUTH_USER_MODEL)),
                ('processing_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='trainers.processingstudent')),
            ],
            options={
                'ordering': ['follow_up_date', 'follow_up_time'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leads.followup')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('JOB_ENQUIRY', 'Job Enquiry'), ('B2B', 'B2B'), ('COLD', 'Cold'), ('WARM', 'Warm'), ('HOT', 'Hot'), ('CLOSED', 'Closed'), ('CONVERTED', 'Converted'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('NOT_INTERESTED', 'Not Interested'), ('CNR', 'Could Not Reach'), ('REGISTERED', 'Registered')], default='ENQUIRY', help_text='Current status of the lead', max_length=20)),
                ('program', models.TextField(blank=True, help_text='Enter the program name', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or comments about the lead', null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, choices=[('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Website'), ('WALK_IN', 'Walk-in'), ('AUTOMATION', 'Automation'), ('OTHER', 'Other'), ('ADS', 'Ads'), ('VOXBAY CALL', 'Voxbay'), ('VOXBAY-EDITORIAL', 'Voxbay-Editorial'), ('IN HOUSE SOCIAL MEDIA', 'In House Social Media'), ('BULK DATA', 'Bulk data')], max_length=50, null=True)),
                ('custom_source', models.CharField(blank=True, max_length=50, null=True)),
                ('voxbay_status', models.CharField(blank=True, max_length=50, null=True)),
                ('interested_country', models.CharField(blank=True, max_length=100, null=True)),
                ('interested_course', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=200, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('adset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_name', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_lead_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('raw_form_data', models.JSONField(blank=True, null=True)),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC'), ('FDS', 'FDS')], db_index=True, default='LP', max_length=10)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded to Processing'), ('ACCEPTED', 'Accepted by Processing'), ('PROCESSING', 'In Processing'), ('COMPLETED', 'Processing Completed'), ('REJECTED', 'Processing Rejected')], default='PENDING', max_length=20)),
                ('processing_status_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('document_status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('VERIFIED', 'Verified'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('documents_received', models.TextField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('sub_assigned_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Who assigned this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Primary assignee (Manager/Department Head)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('processing_executive', models.ForeignKey(blank=True, limit_choices_to={'role': 'PROCESSING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_leads', to=settings.AUTH_USER_MODEL)),
                ('sub_assigned_by', models.ForeignKey(blank=True, help_text='Manager who sub-assigned to junior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_sub_assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('sub_assigned_to', models.ForeignKey(blank=True, help_text='Junior employee handling the lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='followup',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead'),
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('PRIMARY', 'Primary Assignment'), ('SUB', 'Sub Assignment'), ('REASSIGNMENT', 'Reassignment')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_assignments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='leads.lead')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LeadConversionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=200)),
                ('enrollment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_timing', models.CharField(blank=True, max_length=100, null=True)),
                ('total_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_detail', to='leads.lead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Conversion Detail',
            },
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.lead')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded to Processing'), ('ACCEPTED', 'Accepted by Processing'), ('PROCESSING', 'In Processing'), ('COMPLETED', 'Processing Completed'), ('REJECTED', 'Processing Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_updates', to='leads.lead')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RemarkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_remarks', models.TextField(blank=True, null=True)),
                ('new_remarks', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_history', to='leads.lead')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority'], name='leads_lead_priorit_ddce28_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['processing_status'], name='leads_lead_process_39b111_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='leads_lead_assigne_3f8857_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['sub_assigned_to'], name='leads_lead_sub_ass_65f391_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='leads_lead_assigne_92225c_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['follow_up_date'], name='leads_follo_follow__ba7a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status'], name='leads_follo_status_d8909c_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_to'], name='leads_follo_assigne_44c12b_idx'),
        ),
    ]
