# Generated by Django 5.2.4 on 2026-05-29 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_lead_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='leads_lead_assigne_92225c_idx'),
        ),
    ]
