# Generated by Django 5.2.4 on 2026-05-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_lead_leads_lead_assigne_92225c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ad_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='adset_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='meta_lead_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='raw_form_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
