# Generated by Django 5.2.4 on 2026-06-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_leaddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('NOT_INTERESTED', 'Not Interested'), ('CONVERTED', 'Converted'), ('CNR', 'Could Not Reach'), ('REGISTERED', 'Registered')], default='ENQUIRY', help_text='Current status of the lead', max_length=20),
        ),
    ]
