# Generated by Django 5.2.4 on 2026-06-25 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0037_alter_lead_status'),
        ('trainers', '0016_processingstudentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='processing_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='trainers.processingstudent'),
        ),
    ]
