# Generated by Django 5.2.4 on 2026-07-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0038_followup_processing_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='voxbay_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
