# Generated by Django 5.2.4 on 2026-08-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0039_lead_voxbay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FDS')], db_index=True, default='LP', max_length=10),
        ),
    ]
