# Generated by Django 5.2.4 on 2026-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0041_alter_lead_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('not_interested', 'Not Interested'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('JOB_ENQUIRY', 'Job Enquiry'), ('B2B', 'B2B'), ('COLD', 'Cold'), ('WARM', 'Warm'), ('HOT', 'Hot'), ('CLOSED', 'Closed'), ('CONVERTED', 'Converted'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('NOT_INTERESTED', 'Not Interested'), ('CNR', 'Could Not Reach'), ('REGISTERED', 'Registered')], default='ENQUIRY', help_text='Current status of the lead', max_length=20),
        ),
    ]
