# Generated by Django 5.2.4 on 2026-10-08 10:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. A1, A2, B1, B2', max_length=50, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Order for promotion (1 for A1, 2 for A2, etc.)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IntakeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingDynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal field name (e.g., 'medical_check_status')", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Display label (e.g., 'Medical Check Status')", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('choice', 'Choice (Dropdown)')], default='text', max_length=20)),
                ('choices', models.JSONField(blank=True, help_text='List of choices if type is \'choice\' (e.g., ["Pending", "Done"])', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which this field appears in the UI')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(help_text='e.g. 2023-2024', max_length=20)),
                ('grade', models.CharField(blank=True, help_text='e.g. Grade 10', max_length=50, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('model_exam_date', models.DateField(blank=True, null=True)),
                ('final_exam_date', models.DateField(blank=True, null=True)),
                ('default_fee_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_batches', to='fees.feeplantemplate')),
                ('branch', models.ForeignKey(help_text='The branch running this academic batch', on_delete=django.db.models.deletion.PROTECT, related_name='academic_batches', to='trainers.branch')),
                ('starting_level', models.ForeignKey(help_text='The grade at which this batch begins', on_delete=django.db.models.deletion.PROTECT, related_name='starting_academic_batches', to='trainers.courselevel')),
            ],
            options={
                'ordering': ['-academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('maximum_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages_ending_here', to='trainers.courselevel')),
                ('minimum_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages_starting_here', to='trainers.courselevel')),
            ],
            options={
                'ordering': ['minimum_level__order', 'maximum_level__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. A1.1, A1.2', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='trainers.courselevel')),
            ],
            options={
                'ordering': ['level__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_contact', models.CharField(blank=True, help_text='Contact number of parents (1 & 2)', max_length=200, null=True)),
                ('program_applied', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('intake', models.CharField(blank=True, max_length=100, null=True)),
                ('student_file_status', models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Cancelled by Student', 'Cancelled by Student'), ('No Response from Student', 'No Response from Student'), ('File Closed forever', 'File Closed forever')], default='Active', max_length=50)),
                ('registration_fee_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid without gst', 'Paid without gst'), ('Paid with gst', 'Paid with gst')], default='Pending', max_length=50)),
                ('registration_fee_receipt_status', models.CharField(choices=[('Pending', 'Pending'), ('Shared with student', 'Shared with student')], default='Pending', max_length=50)),
                ('enrollment_process_status', models.CharField(choices=[('Pending', 'Pending'), ('Shared', 'Shared'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('application_documents_status', models.CharField(choices=[('Pending', 'Pending'), ('Collected', 'Collected')], default='Pending', max_length=50)),
                ('application_status', models.CharField(blank=True, max_length=200, null=True)),
                ('offer_letter_status', models.CharField(blank=True, max_length=200, null=True)),
                ('visa_appointment_date', models.CharField(blank=True, max_length=200, null=True)),
                ('visa_documentation', models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Complete', 'Complete')], default='Pending', max_length=50)),
                ('visa_results', models.CharField(blank=True, choices=[('', ''), ('Granted', 'Granted'), ('Refused', 'Refused')], max_length=50, null=True)),
                ('category', models.CharField(default='All Students', help_text='e.g., GCC Students', max_length=50)),
                ('processing_fee_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('processing_fee_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('processing_fee_applicable', models.BooleanField(default=False)),
                ('processing_fee_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20, null=True)),
                ('fee_admission_applicable', models.BooleanField(default=False)),
                ('fee_admission_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fee_admission_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fee_admission_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20, null=True)),
                ('fee_language_applicable', models.BooleanField(default=False)),
                ('fee_language_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fee_language_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fee_language_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20, null=True)),
                ('fee_visa_applicable', models.BooleanField(default=False)),
                ('fee_visa_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fee_visa_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fee_visa_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20, null=True)),
                ('fee_ministry_applicable', models.BooleanField(default=False)),
                ('fee_ministry_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fee_ministry_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fee_ministry_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20, null=True)),
                ('dynamic_data', models.JSONField(blank=True, default=dict, help_text='Stores data for dynamically added fields')),
                ('gmail_thread_id', models.CharField(blank=True, help_text='Gmail Thread ID for automated drafts', max_length=100, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_processing_students', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_processing_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'permissions': [('processing_students:read_any', 'Can view any processing student'), ('processing_students:read_own', 'Can view own processing students'), ('processing_students:edit_any', 'Can edit any processing student'), ('processing_students:edit_own', 'Can edit own processing students'), ('processing_students:manage_fees', 'Can manage processing student fees')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='processing_students/documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trainers.processingstudent')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('parent_name', models.CharField(blank=True, help_text="Parent's name", max_length=100, null=True)),
                ('parent_phone', models.CharField(blank=True, help_text="Parent's phone number", max_length=20, null=True)),
                ('mode_of_study', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default='OFFLINE', max_length=20)),
                ('qualification', models.CharField(blank=True, help_text="Student's highest qualification", max_length=150, null=True)),
                ('preferred_country', models.CharField(blank=True, help_text="Student's preferred country for studies", max_length=100, null=True)),
                ('preferred_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('A1-B2', 'A1 to B2'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('batch', models.CharField(blank=True, choices=[('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)'), ('B2', 'B2 (Upper Intermediate)')], max_length=200, null=True)),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('status', models.CharField(choices=[('PENDING_ENROLLMENT', 'Pending Enrollment'), ('PENDING_BATCH_ASSIGNMENT', 'Pending Batch Assignment'), ('ACTIVE', 'Active'), ('EXAM_PREPARATION', 'Exam Preparation'), ('PAUSED', 'Paused'), ('AWAITING_REPEAT_TRANSFER', 'Awaiting Repeat Transfer'), ('AWAITING_PACKAGE_UPGRADE', 'Awaiting Package Upgrade'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='PENDING_ENROLLMENT', max_length=30)),
                ('admission_date', models.DateField(help_text='Admission date')),
                ('start_date', models.DateField(blank=True, help_text='Course start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Course end date', null=True)),
                ('notes', models.TextField(blank=True, help_text='General notes about the student')),
                ('email', models.EmailField(blank=True, help_text="Student's email address", max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text="Student's phone number", max_length=20, null=True)),
                ('drive_link', models.URLField(blank=True, help_text='Google Drive folder link for student materials', null=True)),
                ('student_class', models.CharField(blank=True, help_text='Class type for the student (manual entry)', max_length=50, null=True)),
                ('fee_attendance_policy', models.CharField(choices=[('STRICT', 'Strict (Requires Fee Approval if Overdue)'), ('FLEXIBLE', 'Flexible')], default='FLEXIBLE', help_text='Attendance policy regarding unpaid fees', max_length=20)),
                ('academic_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='trainers.academicbatch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='trainers.branch')),
                ('current_level', models.ForeignKey(blank=True, help_text='Current academic level in the revamped system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='trainers.courselevel')),
            ],
            options={
                'ordering': ['batch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('entry_reason', models.CharField(choices=[('INITIAL', 'Initial Enrollment'), ('PROMOTION', 'Promotion'), ('REPEAT', 'Repeat Transfer'), ('PACKAGE_UPGRADE', 'Package Upgrade')], max_length=30)),
                ('exit_reason', models.CharField(blank=True, choices=[('PROMOTION', 'Promoted'), ('FAILED', 'Failed'), ('PACKAGE_COMPLETE', 'Package Complete'), ('B2_COMPLETE', 'B2 Complete')], max_length=30)),
                ('entered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('exited_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='trainers.academicbatch')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='trainers.courselevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_placements', to='trainers.student')),
            ],
            options={
                'ordering': ['-entered_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('MODEL', 'Model Exam'), ('FINAL', 'Final Exam')], max_length=10)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='PENDING', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='trainers.academicbatch')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_exam_results', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='trainers.student')),
                ('placement', models.ForeignKey(help_text='The student placement for which this exam was taken', on_delete=django.db.models.deletion.PROTECT, related_name='exam_results', to='trainers.studentacademicplacement')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('academic_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_progress', to='trainers.academicbatch')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='trainers.coursemodule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='trainers.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPackageEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REPLACED', 'Replaced')], default='ACTIVE', max_length=20)),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='trainers.academicpackage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_enrollments', to='trainers.student')),
            ],
            options={
                'ordering': ['-started_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='studentacademicplacement',
            name='package_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='trainers.studentpackageenrollment'),
        ),
        migrations.CreateModel(
            name='StudentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BATCH_ASSIGNMENT', 'Batch Assignment'), ('PROMOTE', 'Promote'), ('FALLBACK', 'Fallback'), ('REPEAT_TRANSFER', 'Repeat Transfer'), ('PACKAGE_UPGRADE', 'Package Upgrade'), ('PACKAGE_COMPLETE', 'Package Complete'), ('EXAM_FINALIZED', 'Exam Finalized'), ('STATUS_CHANGE', 'Status Change'), ('NOTE', 'Note')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='trainers.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_link', models.URLField(blank=True, help_text="Link to trainer's Google Drive folder")),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='trainers.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='trainers.trainer'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('NO_SESSION', 'No Session')], default='PRESENT', max_length=15)),
                ('approval_status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING_FEE_APPROVAL', 'Pending Fee Approval')], default='APPROVED', max_length=30)),
                ('approval_notes', models.TextField(blank=True, help_text='Notes regarding the attendance approval (e.g., fee promises)')),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('academic_batch', models.ForeignKey(blank=True, help_text='The batch this student was in when attendance was marked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='trainers.academicbatch')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='trainers.student')),
                ('placement', models.ForeignKey(help_text='Immutable academic placement active when attendance was marked', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='trainers.studentacademicplacement')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='trainers.trainer')),
            ],
            options={
                'ordering': ['-date', 'student__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicbatch',
            constraint=models.UniqueConstraint(fields=('branch', 'name', 'academic_year'), name='unique_academic_batch_name_per_branch_year'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('level', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('placement', 'exam_type')},
        ),
        migrations.AlterUniqueTogether(
            name='studentmoduleprogress',
            unique_together={('student', 'module', 'academic_batch')},
        ),
        migrations.AddConstraint(
            model_name='studentpackageenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student',), name='one_active_academic_package_per_student'),
        ),
        migrations.AddIndex(
            model_name='studentacademicplacement',
            index=models.Index(fields=['academic_batch', 'level', 'status'], name='trainers_st_academi_d4d647_idx'),
        ),
        migrations.AddIndex(
            model_name='studentacademicplacement',
            index=models.Index(fields=['student', 'status'], name='trainers_st_student_d46255_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentacademicplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student',), name='one_active_academic_placement_per_student'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'trainer'], name='trainers_at_date_c68493_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['placement', 'date'], name='trainers_at_placeme_1da730_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('date', 'placement'), name='unique_attendance_per_placement_date'),
        ),
    ]
