# Generated by Django 5.2.4 on 2026-05-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0011_branch_student_branch_trainer_branch_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG')], db_index=True, default='LP', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG')], db_index=True, default='LP', max_length=10),
        ),
    ]
