# Generated by Django 5.2.4 on 2026-06-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('trainers', '0012_attendance_company_student_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicbatch',
            name='default_fee_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_batches', to='fees.feeplantemplate'),
        ),
    ]
