# Generated by Django 5.2.4 on 2026-06-17 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0013_academicbatch_default_fee_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes regarding the attendance approval (e.g., fee promises)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING_FEE_APPROVAL', 'Pending Fee Approval')], default='APPROVED', max_length=30),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='mode_of_study',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default='OFFLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, help_text="Parent's name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, help_text="Parent's phone number", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('A1-B2', 'A1 to B2'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
