# Generated by Django 5.2.4 on 2026-06-25 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0014_attendance_approval_notes_attendance_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingDynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal field name (e.g., 'medical_check_status')", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Display label (e.g., 'Medical Check Status')", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('choice', 'Choice (Dropdown)')], default='text', max_length=20)),
                ('choices', models.JSONField(blank=True, help_text='List of choices if type is \'choice\' (e.g., ["Pending", "Done"])', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which this field appears in the UI')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_contact', models.CharField(blank=True, help_text='Contact number of parents (1 & 2)', max_length=200, null=True)),
                ('program_applied', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('intake', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_fee_status', models.CharField(choices=[('Pending', 'Pending'), ('Shared with student', 'Shared with student'), ('Without Tax amount', 'Without Tax amount')], default='Pending', max_length=50)),
                ('enrollment_process_status', models.CharField(choices=[('Pending', 'Pending'), ('Shared', 'Shared'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('application_documents_status', models.CharField(choices=[('Pending', 'Pending'), ('Collected', 'Collected')], default='Pending', max_length=50)),
                ('application_status', models.CharField(blank=True, max_length=200, null=True)),
                ('offer_letter_status', models.CharField(blank=True, max_length=200, null=True)),
                ('visa_documentation_info_status', models.CharField(blank=True, max_length=200, null=True)),
                ('visa_appointment', models.CharField(blank=True, max_length=200, null=True)),
                ('visa_documentation', models.CharField(blank=True, max_length=200, null=True)),
                ('accommodation', models.CharField(blank=True, max_length=200, null=True)),
                ('visa_results', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(default='All Students', help_text='e.g., GCC Students', max_length=50)),
                ('dynamic_data', models.JSONField(blank=True, default=dict, help_text='Stores data for dynamically added fields')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_processing_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'permissions': [('processing_students:read_any', 'Can view any processing student'), ('processing_students:read_own', 'Can view own processing students'), ('processing_students:edit_any', 'Can edit any processing student'), ('processing_students:edit_own', 'Can edit own processing students')],
            },
        ),
    ]
