# Generated by Django 5.2.4 on 2026-06-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0016_processingstudentdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingstudent',
            options={'ordering': ['-id'], 'permissions': [('processing_students:read_any', 'Can view any processing student'), ('processing_students:read_own', 'Can view own processing students'), ('processing_students:edit_any', 'Can edit any processing student'), ('processing_students:edit_own', 'Can edit own processing students'), ('processing_students:manage_fees', 'Can manage processing student fees')]},
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='processing_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='processing_fee_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='processing_fee_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_attendance_policy',
            field=models.CharField(choices=[('STRICT', 'Strict (Requires Fee Approval if Overdue)'), ('FLEXIBLE', 'Flexible')], default='FLEXIBLE', help_text='Attendance policy regarding unpaid fees', max_length=20),
        ),
    ]
