# Generated by Django 5.2.4 on 2026-07-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0017_alter_processingstudent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('PENDING_ENROLLMENT', 'Pending Enrollment'), ('PENDING_BATCH_ASSIGNMENT', 'Pending Batch Assignment'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='PENDING_ENROLLMENT', max_length=30),
        ),
    ]
