# Generated by Django 5.2.4 on 2026-07-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0018_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='preferred_country',
            field=models.CharField(blank=True, help_text="Student's preferred country for studies", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, help_text="Student's highest qualification", max_length=150, null=True),
        ),
    ]
