# Generated by Django 5.2.4 on 2026-07-11 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0019_student_preferred_country_student_qualification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, choices=[('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)'), ('B2', 'B2 (Upper Intermediate)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('PENDING_ENROLLMENT', 'Pending Enrollment'), ('PENDING_BATCH_ASSIGNMENT', 'Pending Batch Assignment'), ('ACTIVE', 'Active'), ('EXAM_PREPARATION', 'Exam Preparation'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='PENDING_ENROLLMENT', max_length=30),
        ),
        migrations.CreateModel(
            name='StudentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BATCH_ASSIGNMENT', 'Batch Assignment'), ('PROMOTE', 'Promote'), ('FALLBACK', 'Fallback'), ('STATUS_CHANGE', 'Status Change'), ('NOTE', 'Note')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='trainers.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
