# Generated by Django 5.2.4 on 2026-07-20 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0020_alter_student_batch_alter_student_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. A1, A2, B1, B2', max_length=50, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Order for promotion (1 for A1, 2 for A2, etc.)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='academic_batch',
            field=models.ForeignKey(blank=True, help_text='The batch this student was in when attendance was marked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='trainers.academicbatch'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_level',
            field=models.ForeignKey(blank=True, help_text='Current academic level in the revamped system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='trainers.courselevel'),
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. A1.1, A1.2', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='trainers.courselevel')),
            ],
            options={
                'ordering': ['level__order', 'order'],
                'unique_together': {('level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('academic_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_progress', to='trainers.academicbatch')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='trainers.coursemodule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='trainers.student')),
            ],
            options={
                'unique_together': {('student', 'module', 'academic_batch')},
            },
        ),
    ]
