# Generated by Django 5.2.4 on 2026-09-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0024_processingstudent_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingstudent',
            name='registration_fee_receipt_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shared with student', 'Shared with student')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='registration_fee_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid without gst', 'Paid without gst'), ('Paid with gst', 'Paid with gst')], default='Pending', max_length=50),
        ),
    ]
