# Generated by Django 5.2.4 on 2026-09-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0025_processingstudent_registration_fee_receipt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingstudent',
            name='fee_admission_offer_letter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_application_registration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_language_confirmation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_ministry_letter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_visa_approval',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
