# Generated by Django 5.2.4 on 2026-09-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0026_processingstudent_fee_admission_offer_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingstudent',
            name='fee_admission_offer_letter',
        ),
        migrations.RemoveField(
            model_name='processingstudent',
            name='fee_application_registration',
        ),
        migrations.RemoveField(
            model_name='processingstudent',
            name='fee_language_confirmation',
        ),
        migrations.RemoveField(
            model_name='processingstudent',
            name='fee_ministry_letter',
        ),
        migrations.RemoveField(
            model_name='processingstudent',
            name='fee_visa_approval',
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_admission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_admission_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_admission_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_language_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_language_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_language_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_ministry_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_ministry_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_ministry_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_visa_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_visa_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_visa_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
