# Generated by Django 5.2.4 on 2026-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0027_remove_processingstudent_fee_admission_offer_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingstudent',
            name='fee_admission_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_language_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_ministry_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='fee_visa_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processingstudent',
            name='processing_fee_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
