# Generated by Django 5.2.4 on 2026-09-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0028_processingstudent_fee_admission_applicable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_admission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_admission_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_admission_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_admission_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_language_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_language_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_language_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_language_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_ministry_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_ministry_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_ministry_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_ministry_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_visa_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_visa_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_visa_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='fee_visa_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='processing_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='processing_fee_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='processing_fee_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='processing_fee_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20, null=True),
        ),
    ]
