# Generated by Django 5.2.4 on 2026-09-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0029_alter_processingstudent_fee_admission_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingstudent',
            old_name='visa_appointment',
            new_name='visa_appointment_date',
        ),
        migrations.RemoveField(
            model_name='processingstudent',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='processingstudent',
            name='visa_documentation_info_status',
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='visa_documentation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Complete', 'Complete')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='processingstudent',
            name='visa_results',
            field=models.CharField(blank=True, choices=[('', ''), ('Granted', 'Granted'), ('Refused', 'Refused')], max_length=50, null=True),
        ),
    ]
