# Generated by Django 5.2.4 on 2026-09-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0030_rename_visa_appointment_processingstudent_visa_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
