# Generated by Django 5.2.4 on 2026-09-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0031_intakeoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingstudent',
            name='student_file_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Cancelled by the student', 'Cancelled by the student'), ('File closed', 'File closed'), ('File on Hold', 'File on Hold')], default='Active', max_length=50),
        ),
    ]
