# Generated by Django 5.2.4 on 2026-09-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0033_categoryoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingstudent',
            name='student_file_status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Cancelled by Student', 'Cancelled by Student'), ('No Response from Student', 'No Response from Student'), ('File Closed forever', 'File Closed forever')], default='Active', max_length=50),
        ),
    ]
