# Generated by Django 5.2.4 on 2026-10-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0034_alter_processingstudent_student_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingstudent',
            name='gmail_thread_id',
            field=models.CharField(blank=True, help_text='Gmail Thread ID for automated drafts', max_length=100, null=True),
        ),
    ]
