from django.urls import path
from .views import (
    TrainerListCreateAPIView,
    TrainerDetailAPIView,
    TrainerUserListAPIView, 
    StudentListCreateAPIView,
    StudentDetailAPIView,
    AttendanceListCreateAPIView,
    AttendanceDetailAPIView,
    QuickMarkAttendanceAPIView,
    AttendanceRecordsAPIView,
    AttendanceStudentsAPIView, 
    ExportStudentAttendanceAPIView,
    StudentStatsAPIView,
    AcademicBatchListCreateAPIView,
    AcademicBatchDetailAPIView,
    AcademicPackageListCreateAPIView,
    AcademicPackageDetailAPIView,
    BranchListCreateAPIView,
    BranchDetailAPIView,
    ExamResultListCreateAPIView,
    ExamResultDetailAPIView,
    AttendanceApproveAPIView,
    ProcessingStudentListCreateAPIView,
    ProcessingStudentDetailAPIView,
    ProcessingStudentActivityLogAPIView,
    ProcessingStudentNoteAPIView,
    ProcessingDynamicFieldListAPIView,
    ProcessingStudentDocumentListCreateAPIView,
    ProcessingStudentDocumentDeleteAPIView,
    StudentTimelineAPIView,
    StudentAcademicHistoryAPIView,
    StudentPackageUpgradeAPIView,
    AcademicBatchLevelFinalizeAPIView,
    StudentRepeatTransferAPIView,
    CourseLevelListAPIView,
    StudentModuleProgressAPIView,
    AttendanceReportAPIView,
)

urlpatterns = [
    path('trainers/', TrainerListCreateAPIView.as_view(), name='trainer-list-create'),
    path('trainers/<int:pk>/', TrainerDetailAPIView.as_view(), name='trainer-detail'),
    path('trainer-users/', TrainerUserListAPIView.as_view(), name='trainer-user-list'),
    path('academic-batches/', AcademicBatchListCreateAPIView.as_view(), name='academic-batch-list-create'),
    path('academic-batches/<int:pk>/', AcademicBatchDetailAPIView.as_view(), name='academic-batch-detail'),
    path('academic-packages/', AcademicPackageListCreateAPIView.as_view(), name='academic-package-list-create'),
    path('academic-packages/<int:pk>/', AcademicPackageDetailAPIView.as_view(), name='academic-package-detail'),
    path('academic-batches/<int:batch_id>/levels/<int:level_id>/finalize-results/', AcademicBatchLevelFinalizeAPIView.as_view(), name='academic-batch-level-finalize'),
    path('students/', StudentListCreateAPIView.as_view(), name='student-list-create'),
    path('students/<int:pk>/', StudentDetailAPIView.as_view(), name='student-detail'),
    path('students/<int:pk>/timeline/', StudentTimelineAPIView.as_view(), name='student-timeline'),
    path('students/<int:pk>/academic-history/', StudentAcademicHistoryAPIView.as_view(), name='student-academic-history'),
    path('students/<int:pk>/academic-package/', StudentPackageUpgradeAPIView.as_view(), name='student-academic-package-upgrade'),
    path('students/<int:pk>/repeat-transfer/', StudentRepeatTransferAPIView.as_view(), name='student-repeat-transfer'),
    path('students/<int:pk>/module-progress/', StudentModuleProgressAPIView.as_view(), name='student-module-progress'),
    path('course-levels/', CourseLevelListAPIView.as_view(), name='course-levels'),
    path('attendance/', AttendanceListCreateAPIView.as_view(), name='attendance-list-create'),
    path('attendance/detail/', AttendanceDetailAPIView.as_view(), name='attendance-detail'),
    path('attendance/quick-mark/', QuickMarkAttendanceAPIView.as_view(), name='attendance-quick-mark'),
    path('attendance/students/', AttendanceStudentsAPIView.as_view(), name='attendance-students'), 
    path('attendance/student/<int:student_id>/', AttendanceRecordsAPIView.as_view(), name='attendance-student-records'),
    path('attendance/<int:pk>/approve/', AttendanceApproveAPIView.as_view(), name='attendance-approve'),
    path('attendance/export/<int:student_id>/', ExportStudentAttendanceAPIView.as_view(), name='export-student-attendance'),
    path('attendance/reports/', AttendanceReportAPIView.as_view(), name='attendance-report'),
    path('stats/students/', StudentStatsAPIView.as_view(), name='student-stats'),
    path('branches/', BranchListCreateAPIView.as_view(), name='branch-list-create'),
    path('branches/<int:pk>/', BranchDetailAPIView.as_view(), name='branch-detail'),
    path('exam-results/', ExamResultListCreateAPIView.as_view(), name='exam-result-list-create'),
    path('exam-results/<int:pk>/', ExamResultDetailAPIView.as_view(), name='exam-result-detail'),
    path('processing-students/', ProcessingStudentListCreateAPIView.as_view(), name='processing-student-list-create'),
    path('processing-students/<int:pk>/', ProcessingStudentDetailAPIView.as_view(), name='processing-student-detail'),
    path('processing-students/<int:pk>/activity/', ProcessingStudentActivityLogAPIView.as_view(), name='processing-student-activity'),
    path('processing-students/<int:pk>/note/', ProcessingStudentNoteAPIView.as_view(), name='processing-student-note'),
    path('processing-students/<int:pk>/documents/', ProcessingStudentDocumentListCreateAPIView.as_view(), name='processing-student-documents'),
    path('processing-student-documents/<int:pk>/', ProcessingStudentDocumentDeleteAPIView.as_view(), name='processing-student-document-delete'),
    path('processing-students/dynamic-fields/', ProcessingDynamicFieldListAPIView.as_view(), name='processing-student-dynamic-fields'),
]
