# Generated by Django 5.2.4 on 2026-09-02 07:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('grace_absences', models.PositiveSmallIntegerField(default=0)),
                ('fee_block_on_pending', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance Policies',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate')], max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(help_text='1=A1, 2=A2, 3=B1, 4=B2', unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AcademicBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('proposed', 'Proposed'), ('closed', 'Closed'), ('promoted', 'Promoted')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_batches', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='students.academicpackage')),
                ('attendance_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='students.attendancepolicy')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='students.campus')),
                ('current_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches_current', to='students.grade')),
                ('starting_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches_starting', to='students.grade')),
            ],
            options={
                'ordering': ['campus', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='students.academicbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('batch', 'date')},
            },
        ),
        migrations.AddField(
            model_name='academicpackage',
            name='ending_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages_ending', to='students.grade'),
        ),
        migrations.AddField(
            model_name='academicpackage',
            name='starting_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages_starting', to='students.grade'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('parent_phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(default='FLAG', editable=False, max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('demoted', 'Demoted - Awaiting Reassignment'), ('exited', 'Exited'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('mode_of_study', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.academicpackage')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.academicbatch')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.campus')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_events', to='students.academicbatch')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_from', to='students.grade')),
                ('new_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_promotions', to='students.academicbatch')),
                ('to_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_to', to='students.grade')),
                ('exited_students', models.ManyToManyField(blank=True, related_name='exits', to='students.student')),
                ('promoted_students', models.ManyToManyField(blank=True, related_name='promotions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='GradeExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('model_exam_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_exam_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('model_exam_max', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('grade_exam_max', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Result Pending')], default='pending', max_length=10)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='students.academicbatch')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_records', to='students.grade')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='students.student')),
            ],
            options={
                'ordering': ['-attempt_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('reassigned', models.BooleanField(default=False)),
                ('reassigned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demotions_from', to='students.academicbatch')),
                ('to_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demotions_to', to='students.academicbatch')),
                ('from_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demotions_from', to='students.grade')),
                ('to_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demotions_to', to='students.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demotion_events', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('enrolled', 'Enrolled'), ('promoted', 'Promoted'), ('demoted', 'Demoted'), ('exited', 'Exited'), ('transferred', 'Transferred')], max_length=20)),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='students.academicbatch')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grade_at_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_history', to='students.student')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('pending', 'Pending (Fee Due)'), ('leave', 'Approved Leave')], default='absent', max_length=10)),
                ('is_regularized', models.BooleanField(default=False)),
                ('regularized_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('regularized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularized_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='students.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
    ]
