# Generated by Django 5.2.4 on 2026-09-27 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_sync_student_batch_trainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='students.grade'),
        ),
    ]
