# Generated by Django 5.2.4 on 2026-08-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studenttimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchattendance',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.academicgrade'),
        ),
    ]
