# Generated by Django 5.2.4 on 2026-08-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_batchattendance_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicbatch',
            name='schedule',
            field=models.CharField(blank=True, help_text='e.g., Morning, Evening, Weekend', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academicbatch',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicbatch',
            name='starting_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches_started', to='students.academicgrade'),
        ),
        migrations.AddField(
            model_name='academicbatch',
            name='target_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
