# Generated by Django 5.2.4 on 2026-08-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_trainer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_type',
            field=models.CharField(choices=[('MODEL', 'Model Exam'), ('MAIN', 'Main Exam')], default='MAIN', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'batch', 'grade', 'exam_type')},
        ),
    ]
