# Generated by Django 5.2.4 on 2026-06-04 05:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0012_attendance_company_student_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('due_date', models.DateField(db_index=True)),
                ('scheduled_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='FeePlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG')], db_index=True, default='LP', max_length=10)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('course_label', models.CharField(blank=True, max_length=150)),
                ('plan_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('INSTALLMENT', 'Installment'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom'), ('PACKAGE', 'Package')], default='CUSTOM', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('registration_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('installment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('due_day', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['company', 'name'],
                'indexes': [models.Index(fields=['company', 'plan_type'], name='fees_feepla_company_a41c92_idx'), models.Index(fields=['company', 'course_label'], name='fees_feepla_company_b22f8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG')], db_index=True, default='LP', max_length=10)),
                ('plan_code', models.CharField(blank=True, max_length=80)),
                ('plan_name', models.CharField(blank=True, max_length=150)),
                ('plan_type', models.CharField(default='CUSTOM', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('OVERDUE', 'Overdue'), ('SETTLED', 'Settled'), ('RESTRUCTURED', 'Restructured'), ('WAIVED', 'Waived')], db_index=True, default='ACTIVE', max_length=20)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('registration_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_day', models.PositiveIntegerField(default=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_restructure_date', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_label', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('plan_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_accounts', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_account', to='trainers.student')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_accounts', to='fees.feeplantemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fee_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG')], db_index=True, default='LP', max_length=10)),
                ('receipt_number', models.CharField(max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments_created', to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='fees.feeinstallment')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.studentfeeaccount')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fees.studentfeeaccount'),
        ),
        migrations.CreateModel(
            name='FeeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('WAIVER', 'Waiver'), ('REFUND', 'Refund'), ('RESTRUCTURE', 'Restructure'), ('CONCESSION', 'Concession'), ('MANUAL', 'Manual')], max_length=20)),
                ('amount_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='fees.studentfeeaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentfeeaccount',
            index=models.Index(fields=['company', 'status'], name='fees_studen_company_9365d4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeaccount',
            index=models.Index(fields=['company', 'next_due_date'], name='fees_studen_company_934d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['company', 'payment_date'], name='fees_feepay_company_9074b9_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['account', 'payment_date'], name='fees_feepay_account_74a259_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinstallment',
            index=models.Index(fields=['account', 'status'], name='fees_feeins_account_ca0f02_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinstallment',
            index=models.Index(fields=['due_date', 'status'], name='fees_feeins_due_dat_e1574c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feeinstallment',
            unique_together={('account', 'sequence_number')},
        ),
        migrations.AddIndex(
            model_name='feeadjustment',
            index=models.Index(fields=['adjustment_type'], name='fees_feeadj_adjustm_638921_idx'),
        ),
        migrations.AddIndex(
            model_name='feeadjustment',
            index=models.Index(fields=['created_at'], name='fees_feeadj_created_ab950d_idx'),
        ),
    ]
