# Generated by Django 5.2.4 on 2026-06-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='LP', max_length=10, unique=True)),
                ('block_without_fee_account', models.BooleanField(default=False)),
                ('pending_if_overdue', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Fee Policies',
            },
        ),
    ]
