# Generated by Django 5.2.4 on 2026-08-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_studentfeeaccount_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10),
        ),
        migrations.AlterField(
            model_name='feeplantemplate',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentfeeaccount',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10),
        ),
    ]
