# Generated by Django 5.2.4 on 2026-09-28 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_feepayment_company_and_more'),
        ('students', '0003_attendancesession_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeeaccount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_accounts', to='students.student'),
        ),
    ]
