# Generated by Django 5.2.4 on 2026-09-28 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_alter_studentfeeaccount_student'),
        ('students', '0003_attendancesession_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeeaccount',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_accounts', to='students.grade'),
        ),
    ]
