# Generated by Django 5.2.4 on 2026-10-08 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('classification', models.CharField(blank=True, help_text='Grouping classification (e.g., Communication Systems, System Classification)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Document Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('month', models.CharField(max_length=100, verbose_name='Month')),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('document', models.FileField(blank=True, help_text='Upload attendance document (PDF, Excel, Image, etc.)', null=True, upload_to='attendance_documents/', verbose_name='Attendance Document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Document',
                'verbose_name_plural': 'Attendance Documents',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('position_applied', models.CharField(max_length=255)),
                ('resume', models.FileField(blank=True, null=True, upload_to='hr/candidate_resumes/')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, help_text='Rate candidate out of 10', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('document_type', models.CharField(help_text='e.g. License, Contract, Certification', max_length=100, verbose_name='Document Type')),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('expired', 'Expired')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('renewal_interval_days', models.PositiveIntegerField(blank=True, help_text='e.g. 365 for annual. Used to compute next renewal date.', null=True, verbose_name='Renewal Interval (Days)')),
                ('next_renewal_date', models.DateField(blank=True, null=True, verbose_name='Next Renewal Date')),
                ('company', models.CharField(choices=[('LP', 'LP (All Branches)'), ('LP_HQ', 'LP — HQ'), ('LP_KOCHI', 'LP — Kochi'), ('FLAG', 'FLAG'), ('FLAG_KOCHI', 'FLAG — Kochi'), ('FDS', 'FDS (All Branches)'), ('FDS_KOCHI', 'FDS — Kochi')], db_index=True, default='LP', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Detail',
                'verbose_name_plural': 'Document Details',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Late Report, Missing Agenda', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Person responsible for this space', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='hr.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('provider', models.CharField(blank=True, help_text='Telecom Provider (for SIM Cards)', max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='hr/assets/', verbose_name='Asset Photo/Invoice')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member currently holding this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('primary_sim', models.ForeignKey(blank=True, help_text='Primary SIM assigned to this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='hr.asset')),
                ('secondary_sim', models.ForeignKey(blank=True, help_text='Secondary SIM assigned to this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_for', to='hr.asset')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hr.assetcategory')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this asset belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hr.branch')),
                ('assigned_location', models.ForeignKey(blank=True, help_text='Physical location where this asset is placed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hr.location')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('act', models.CharField(max_length=1000)),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='Amount')),
                ('month', models.CharField(max_length=100, verbose_name='Month')),
                ('date', models.DateField()),
                ('source_report_id', models.IntegerField(blank=True, help_text='ID of the DailyReport that triggered this penalty', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
                'ordering': ['-date'],
            },
        ),
    ]
