# Generated by Django 5.2.4 on 2026-06-01 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, help_text='Parent asset this is attached to (e.g. Mobile for a SIM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_assets', to='hr.asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Monitors', 'Monitors'), ('PC', 'PC'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Laptops', 'Laptops'), ('SIM', 'SIM')], max_length=100),
        ),
    ]
