# Generated by Django 5.2.4 on 2026-06-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_asset_parent_asset_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='hr/assets/', verbose_name='Asset Photo/Invoice'),
        ),
        migrations.AlterField(
            model_name='attendancedocument',
            name='document',
            field=models.FileField(blank=True, help_text='Upload attendance document (PDF, Excel, Image, etc.)', null=True, upload_to='attendance_documents/', verbose_name='Attendance Document'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='hr/candidate_resumes/'),
        ),
    ]
