# Generated by Django 5.2.4 on 2026-06-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_assetcategory_location_asset_primary_phone_number_and_more'),
    ]

    def migrate_asset_categories(apps, schema_editor):
        Asset = apps.get_model('hr', 'Asset')
        AssetCategory = apps.get_model('hr', 'AssetCategory')

        # Default categories based on the previous hardcoded list and new needs
        default_categories = ['Mobiles', 'Monitors', 'PC', 'Keyboard', 'Mouse', 'Laptops', 'SIM', 'AC', 'Teapoy', 'Waste Bin']
        for cat_name in default_categories:
            AssetCategory.objects.get_or_create(name=cat_name)

        # Map existing assets
        for asset in Asset.objects.all():
            if asset.asset_type:
                category, _ = AssetCategory.objects.get_or_create(name=asset.asset_type)
                asset.category = category
                asset.save()

    def reverse_migrate(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(migrate_asset_categories, reverse_migrate),
    ]
