# Generated by Django 5.2.4 on 2026-06-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_auto_20260613_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
    ]
