# Generated by Django 5.2.4 on 2026-06-13 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_branch_location_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this asset belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hr.branch'),
        ),
    ]
