# Generated by Django 5.2.4 on 2026-06-13 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_asset_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='parent_asset',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='primary_phone_number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='secondary_phone_number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.AddField(
            model_name='asset',
            name='primary_sim',
            field=models.ForeignKey(blank=True, help_text='Primary SIM assigned to this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='hr.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='provider',
            field=models.CharField(blank=True, help_text='Telecom Provider (for SIM Cards)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='secondary_sim',
            field=models.ForeignKey(blank=True, help_text='Secondary SIM assigned to this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_for', to='hr.asset'),
        ),
    ]
