# Generated by Django 5.2.4 on 2026-09-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_alter_asset_company_alter_branch_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('document_type', models.CharField(help_text='e.g. License, Contract, Certification', max_length=100, verbose_name='Document Type')),
                ('description', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Detail',
                'verbose_name_plural': 'Document Details',
                'ordering': ['expiry_date'],
            },
        ),
    ]
