# Generated by Django 5.2.4 on 2026-09-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_documentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetail',
            name='next_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Renewal Date'),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='renewal_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 365 for annual. Used to compute next renewal date.', null=True, verbose_name='Renewal Interval (Days)'),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('expired', 'Expired')], db_index=True, default='active', max_length=20, verbose_name='Status'),
        ),
    ]
