# Generated by Django 5.2.4 on 2026-10-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_documentdetail_next_renewal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdetail',
            name='company',
            field=models.CharField(choices=[('LP', 'LP (All Branches)'), ('LP_HQ', 'LP — HQ'), ('LP_KOCHI', 'LP — Kochi'), ('FLAG', 'FLAG'), ('FLAG_KOCHI', 'FLAG — Kochi'), ('FDS', 'FDS (All Branches)'), ('FDS_KOCHI', 'FDS — Kochi')], db_index=True, default='LP', max_length=20),
        ),
    ]
