# Generated by Django on 2026-10-06

from django.db import migrations, models

CLASSIFICATION_MAP = {
    # Communication Systems
    'mobiles': 'Communication Systems',
    'mobile phones': 'Communication Systems',
    'sim': 'Communication Systems',
    'sim card': 'Communication Systems',
    'phone': 'Communication Systems',
    'telephone': 'Communication Systems',
    'smartphone': 'Communication Systems',
    'tablet': 'Communication Systems',

    # System Classification
    'cpu': 'System Classification',
    'keyboard': 'System Classification',
    'mouse': 'System Classification',
    'pc': 'System Classification',
    'laptop': 'System Classification',
    'laptops': 'System Classification',
    'lap charger': 'System Classification',
    'moniter': 'System Classification',
    'monitors': 'System Classification',
    'monitor': 'System Classification',
    'wify adaptor': 'System Classification',
    'wifi adaptor': 'System Classification',
    'wifi adapter': 'System Classification',
    'hard drive': 'System Classification',
    'hard disk': 'System Classification',
    'ram': 'System Classification',
    'desktop': 'System Classification',

    # Office Furniture
    'chair': 'Office Furniture',
    'office chair': 'Office Furniture',
    'table': 'Office Furniture',
    'teapoy': 'Office Furniture',
    'sofa': 'Office Furniture',
    'shelf': 'Office Furniture',
    'stand': 'Office Furniture',
    'desk': 'Office Furniture',
    'cupboard': 'Office Furniture',

    # Electronics & Appliances
    'ac': 'Electronics & Appliances',
    'fan': 'Electronics & Appliances',
    'tv & remote': 'Electronics & Appliances',
    'home theatre': 'Electronics & Appliances',
    'speaker': 'Electronics & Appliances',
    'ups': 'Electronics & Appliances',
    'projector': 'Electronics & Appliances',

    # Office Equipment & Utilities
    'printer': 'Office Equipment & Utilities',
    'camera': 'Office Equipment & Utilities',
    'white board': 'Office Equipment & Utilities',
    'id card': 'Office Equipment & Utilities',
    'key set box': 'Office Equipment & Utilities',
    'waste in': 'Office Equipment & Utilities',
    'waste bin': 'Office Equipment & Utilities',
    'scanner': 'Office Equipment & Utilities',
}

def populate_classifications(apps, schema_editor):
    AssetCategory = apps.get_model('hr', 'AssetCategory')
    for cat in AssetCategory.objects.all():
        clean_name = (cat.name or '').strip().lower()
        cat.classification = CLASSIFICATION_MAP.get(clean_name, 'General Assets')
        cat.save(update_fields=['classification'])

def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_document_add_branch_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='classification',
            field=models.CharField(
                blank=True,
                help_text='Grouping classification (e.g., Communication Systems, System Classification)',
                max_length=100,
                null=True
            ),
        ),
        migrations.RunPython(populate_classifications, reverse_populate),
    ]
