# Generated by Django 5.2.4 on 2026-10-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_assetcategory_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetail',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount'),
        ),
    ]
