# Generated by Django 5.2.4 on 2026-10-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_document_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Late Report, Missing Agenda', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='penalty',
            name='source_report_id',
            field=models.IntegerField(blank=True, help_text='ID of the DailyReport that triggered this penalty', null=True),
        ),
    ]
