# Generated by Django 5.2.4 on 2026-06-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_credentialcategory_credential_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='web_mail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
