# Generated by Django 5.2.4 on 2026-10-08 10:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. leads:read_all, leads:edit_tenant', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('team', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_on_leave', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('voxbay_number', models.CharField(blank=True, help_text='The Agent Number or DID assigned to this user in Voxbay', max_length=30, null=True)),
                ('voxbay_extension', models.CharField(blank=True, help_text='The extension mapped to this user in Voxbay (used for Click-to-Call)', max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='profile_pics/%Y/%m/')),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('extra_permissions', models.TextField(blank=True, default='[]')),
                ('gmail_credentials', models.JSONField(blank=True, default=dict, help_text='Stores Gmail OAuth2 credentials (access_token, refresh_token, etc)', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MicroWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('job_title', models.CharField(help_text='Title of the micro work', max_length=200, verbose_name='Job Title')),
                ('description', models.TextField(help_text='Detailed description of the work', verbose_name='Description')),
                ('time_required', models.CharField(help_text='Estimated time required (e.g., 2 hours, 30 minutes)', max_length=100, verbose_name='Time Required')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Micro Work',
                'verbose_name_plural': 'Micro Works',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.ManyToManyField(blank=True, db_table='role_permissions', related_name='roles', to='accounts.apppermission')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='db_roles',
            field=models.ManyToManyField(blank=True, db_table='user_roles', related_name='users', to='accounts.role'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('action', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('LEAD_STATUS_CHANGED', 'Lead Status Changed'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_SUB_ASSIGNED', 'Lead Sub-Assigned'), ('LEAD_UNASSIGNED', 'Lead Unassigned'), ('LEAD_PROCESSING_UPDATED', 'Lead Processing Updated'), ('LEAD_REMARK_UPDATED', 'Lead Remark Updated'), ('LEAD_DELETED', 'Lead Deleted'), ('FOLLOWUP_CREATED', 'Follow-Up Created'), ('FOLLOWUP_STATUS_CHANGED', 'Follow-Up Status Changed'), ('FOLLOWUP_CONVERTED', 'Follow-Up Converted to Lead'), ('FOLLOWUP_DELETED', 'Follow-Up Deleted'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_OVERDUE', 'Task Marked Overdue'), ('TASK_DELETED', 'Task Deleted'), ('STAFF_CREATED', 'Staff Created'), ('STAFF_UPDATED', 'Staff Updated'), ('STAFF_ACTIVATED', 'Staff Activated'), ('STAFF_DEACTIVATED', 'Staff Deactivated'), ('STAFF_DELETED', 'Staff Deleted'), ('USER_LOGIN', 'User Logged In'), ('USER_LOGOUT', 'User Logged Out'), ('MICROWORK_CREATED', 'Micro Work Created'), ('MICROWORK_COMPLETED', 'Micro Work Completed'), ('MICROWORK_DELETED', 'Micro Work Deleted'), ('TRAINER_CREATED', 'Trainer Profile Created'), ('TRAINER_UPDATED', 'Trainer Profile Updated'), ('TRAINER_STATUS_CHANGED', 'Trainer Status Changed'), ('TRAINER_DELETED', 'Trainer Profile Deleted'), ('STUDENT_ENROLLED', 'Student Enrolled'), ('STUDENT_UPDATED', 'Student Updated'), ('STUDENT_COMPLETED', 'Student Completed Course'), ('STUDENT_DROPPED', 'Student Dropped'), ('STUDENT_PAUSED', 'Student Paused'), ('STUDENT_REACTIVATED', 'Student Reactivated'), ('STUDENT_TRAINER_CHANGED', 'Student Trainer Changed'), ('STUDENT_BATCH_CHANGED', 'Student Batch Changed'), ('STUDENT_DELETED', 'Student Deleted'), ('PROCESSING_STUDENT_CREATED', 'Processing Student Created'), ('PROCESSING_STUDENT_UPDATED', 'Processing Student Updated'), ('PROCESSING_STUDENT_DELETED', 'Processing Student Deleted'), ('PROCESSING_STUDENT_NOTE', 'Processing Student Note Added'), ('ATTENDANCE_MARKED', 'Attendance Marked'), ('ATTENDANCE_UPDATED', 'Attendance Updated'), ('PENALTY_ISSUED', 'Penalty Issued'), ('PENALTY_UPDATED', 'Penalty Updated'), ('PENALTY_DELETED', 'Penalty Deleted'), ('ATTENDANCE_DOC_UPLOADED', 'Attendance Document Uploaded'), ('ATTENDANCE_DOC_DELETED', 'Attendance Document Deleted'), ('ASSET_CREATED', 'Asset Created'), ('ASSET_UPDATED', 'Asset Updated'), ('ASSET_ASSIGNED', 'Asset Assigned'), ('ASSET_UNASSIGNED', 'Asset Unassigned'), ('ASSET_DELETED', 'Asset Deleted')], db_index=True, max_length=60)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='accounts_ac_action_fde492_idx'), models.Index(fields=['entity_type'], name='accounts_ac_entity__3bd5b2_idx'), models.Index(fields=['created_at'], name='accounts_ac_created_936747_idx')],
            },
        ),
    ]
