# Generated by Django 5.2.4 on 2026-05-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG')], db_index=True, default='LP', max_length=10),
        ),
        migrations.AddField(
            model_name='microwork',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG')], db_index=True, default='LP', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG')], db_index=True, default='LP', max_length=10),
        ),
    ]
