# Generated by Django 5.2.4 on 2026-06-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_activitylog_company_microwork_company_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('LEAD_STATUS_CHANGED', 'Lead Status Changed'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_SUB_ASSIGNED', 'Lead Sub-Assigned'), ('LEAD_UNASSIGNED', 'Lead Unassigned'), ('LEAD_PROCESSING_UPDATED', 'Lead Processing Updated'), ('LEAD_REMARK_UPDATED', 'Lead Remark Updated'), ('LEAD_DELETED', 'Lead Deleted'), ('FOLLOWUP_CREATED', 'Follow-Up Created'), ('FOLLOWUP_STATUS_CHANGED', 'Follow-Up Status Changed'), ('FOLLOWUP_CONVERTED', 'Follow-Up Converted to Lead'), ('FOLLOWUP_DELETED', 'Follow-Up Deleted'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_OVERDUE', 'Task Marked Overdue'), ('TASK_DELETED', 'Task Deleted'), ('STAFF_CREATED', 'Staff Created'), ('STAFF_UPDATED', 'Staff Updated'), ('STAFF_ACTIVATED', 'Staff Activated'), ('STAFF_DEACTIVATED', 'Staff Deactivated'), ('STAFF_DELETED', 'Staff Deleted'), ('USER_LOGIN', 'User Logged In'), ('USER_LOGOUT', 'User Logged Out'), ('MICROWORK_CREATED', 'Micro Work Created'), ('MICROWORK_COMPLETED', 'Micro Work Completed'), ('MICROWORK_DELETED', 'Micro Work Deleted'), ('TRAINER_CREATED', 'Trainer Profile Created'), ('TRAINER_UPDATED', 'Trainer Profile Updated'), ('TRAINER_STATUS_CHANGED', 'Trainer Status Changed'), ('TRAINER_DELETED', 'Trainer Profile Deleted'), ('STUDENT_ENROLLED', 'Student Enrolled'), ('STUDENT_UPDATED', 'Student Updated'), ('STUDENT_COMPLETED', 'Student Completed Course'), ('STUDENT_DROPPED', 'Student Dropped'), ('STUDENT_PAUSED', 'Student Paused'), ('STUDENT_REACTIVATED', 'Student Reactivated'), ('STUDENT_TRAINER_CHANGED', 'Student Trainer Changed'), ('STUDENT_BATCH_CHANGED', 'Student Batch Changed'), ('STUDENT_DELETED', 'Student Deleted'), ('ATTENDANCE_MARKED', 'Attendance Marked'), ('ATTENDANCE_UPDATED', 'Attendance Updated'), ('PENALTY_ISSUED', 'Penalty Issued'), ('PENALTY_UPDATED', 'Penalty Updated'), ('PENALTY_DELETED', 'Penalty Deleted'), ('ATTENDANCE_DOC_UPLOADED', 'Attendance Document Uploaded'), ('ATTENDANCE_DOC_DELETED', 'Attendance Document Deleted'), ('ASSET_CREATED', 'Asset Created'), ('ASSET_UPDATED', 'Asset Updated'), ('ASSET_ASSIGNED', 'Asset Assigned'), ('ASSET_UNASSIGNED', 'Asset Unassigned'), ('ASSET_DELETED', 'Asset Deleted')], db_index=True, max_length=60),
        ),
    ]
