# Generated by Django 5.2.4 on 2026-06-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_apppermission_role_user_db_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_permissions',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
