# Generated by Django 5.2.4 on 2026-06-06 09:36

from django.db import migrations


def migrate_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Role = apps.get_model('accounts', 'Role')
    
    for user in User.objects.all():
        if user.role:
            role_obj, created = Role.objects.get_or_create(
                name=user.role,
                defaults={'description': f'Migrated legacy role: {user.role}'}
            )
            user.db_roles.add(role_obj)

def reverse_migrate_roles(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_extra_permissions'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_migrate_roles),
    ]
