# Generated by Django 5.2.4 on 2026-06-09 10:31

from django.db import migrations

def migrate_legacy_permissions(apps, schema_editor):
    AppPermission = apps.get_model('accounts', 'AppPermission')
    
    mapping = {
        'view_my_reports': 'reports:read_own',
        'view_staff_reports': 'reports:read_all',
        'view_all_tasks': 'tasks:read_all',
        'view_my_tasks': 'tasks:read_own',
        'edit_tasks': 'tasks:edit_any',
        'manage_asset': 'assets:manage',
        'view_asset': 'assets:read_any',
        'view_staff_assets': 'assets:read_tenant',
        'edit_penalties': 'penalties:edit_any',
        'view_penalties': 'penalties:read_any',
        'view_candidates': 'candidates:read_any',
        'edit_candidates': 'candidates:edit_any',
        'view_overview': 'dashboard:read',
        'view_staff': 'staff:read_tenant',
        'edit_staff': 'staff:edit_any',
        'delete_staff': 'staff:delete_any',
        'view_leads': 'leads:read_tenant',
        'view_students': 'students:read_tenant',
        'edit_students': 'students:edit_any',
        'view_fees': 'fees:read_tenant',
        'manage_fees': 'fees:manage',
        'restructure_fees': 'fees:restructure',
        'record_partial_payment': 'fees:partial_payment',
        'issue_fee_notice': 'fees:issue_notice',
        'view_fee_reports': 'fees:view_reports',
        'mark_attendance': 'attendance:mark',
        'view_attendance_docs': 'attendance:view_docs',
        'view_voxbay': 'voxbay:read',
        'access_flag': 'staff:access_flag',
        'edit_staff_contact_logic': 'staff:edit_contact_logic'
    }

    for legacy, new_val in mapping.items():
        legacy_perm = AppPermission.objects.filter(name=legacy).first()
        if not legacy_perm:
            continue
            
        new_perm = AppPermission.objects.filter(name=new_val).first()
        
        if new_perm:
            # Transfer roles from legacy_perm to new_perm
            for role in legacy_perm.roles.all():
                role.permissions.add(new_perm)
            # Delete the legacy permission since it's now redundant
            legacy_perm.delete()
        else:
            # Just rename it if the new one doesn't exist
            legacy_perm.name = new_val
            legacy_perm.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_user_role'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_permissions, reverse_code=migrations.RunPython.noop),
    ]
