# Generated by Django 5.2.4 on 2026-06-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_migrate_legacy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
