# Generated by Django 5.2.4 on 2026-06-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_is_on_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voxbay_number',
            field=models.CharField(blank=True, help_text='The Agent Number or DID assigned to this user in Voxbay', max_length=30, null=True),
        ),
    ]
