# Generated by Django 5.2.4 on 2026-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_user_voxbay_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voxbay_extension',
            field=models.CharField(blank=True, help_text='The extension mapped to this user in Voxbay (used for Click-to-Call)', max_length=20, null=True),
        ),
    ]
