# Generated by Django on 2026-06-30 06:33

from django.db import migrations

def seed_accountant_fees_perms(apps, schema_editor):
    AppPermission = apps.get_model('accounts', 'AppPermission')
    Role = apps.get_model('accounts', 'Role')

    fee_perms = [
        {'name': 'fees:manage', 'description': 'Can fully manage fees (create, edit, delete)'},
        {'name': 'fees:read_tenant', 'description': 'Can view all fees in the tenant/company'},
        {'name': 'fees:restructure', 'description': 'Can restructure fees'},
        {'name': 'fees:partial_payment', 'description': 'Can accept partial payments'},
        {'name': 'fees:issue_notice', 'description': 'Can issue fee notices'},
        {'name': 'fees:view_reports', 'description': 'Can view fee reports'},
        {'name': 'fees:read_own', 'description': 'Can read own fees'},
    ]
    
    perms_to_add = []
    for p in fee_perms:
        obj, _ = AppPermission.objects.get_or_create(name=p['name'], defaults={'description': p['description']})
        if p['name'] in ['fees:manage', 'fees:read_tenant', 'fees:restructure', 'fees:partial_payment', 'fees:view_reports']:
            perms_to_add.append(obj)

    accountant_roles = Role.objects.filter(name='ACCOUNTANT')
    for role in accountant_roles:
        role.permissions.add(*perms_to_add)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_activitylog_action'),
    ]

    operations = [
        migrations.RunPython(seed_accountant_fees_perms, reverse_code=migrations.RunPython.noop),
    ]
