# Generated by Django 5.2.4 on 2026-08-11 08:53

from django.db import migrations

def seed_students_perms(apps, schema_editor):
    AppPermission = apps.get_model('accounts', 'AppPermission')
    Role = apps.get_model('accounts', 'Role')

    student_perms = [
        {'name': 'students:registry_manage', 'description': 'Can add/edit students and manage their registry packages'},
        {'name': 'students:batch_manage', 'description': 'Can manage academic batches and grades'},
        {'name': 'attendance:mark', 'description': 'Can mark daily batch attendance'},
        {'name': 'attendance:approvals', 'description': 'Can approve strict fee attendance dues'},
    ]
    
    perms_to_add = []
    for p in student_perms:
        obj, _ = AppPermission.objects.get_or_create(name=p['name'], defaults={'description': p['description']})
        perms_to_add.append(obj)

    # Let's optionally attach them to ACCOUNTANT and TRAINER roles if they exist
    accountant_roles = Role.objects.filter(name='ACCOUNTANT')
    trainer_roles = Role.objects.filter(name='TRAINER')

    # Accounts gets registry and approvals
    accounts_perms = [p for p in perms_to_add if p.name in ['students:registry_manage', 'attendance:approvals']]
    for role in accountant_roles:
        role.permissions.add(*accounts_perms)

    # Trainer gets batch manage and attendance mark
    trainer_perms = [p for p in perms_to_add if p.name in ['students:batch_manage', 'attendance:mark']]
    for role in trainer_roles:
        role.permissions.add(*trainer_perms)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_user_profile_picture'),
    ]

    operations = [
        migrations.RunPython(seed_students_perms, reverse_code=migrations.RunPython.noop),
    ]
