# Generated by Django 5.2.4 on 2026-08-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_students_module_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10),
        ),
        migrations.AlterField(
            model_name='microwork',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10),
        ),
    ]
