# Generated by Django 5.2.4 on 2026-10-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_seed_fds_management_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail_credentials',
            field=models.JSONField(blank=True, default=dict, help_text='Stores Gmail OAuth2 credentials (access_token, refresh_token, etc)', null=True),
        ),
    ]
