# Generated by Django 5.2.4 on 2026-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='feeds/media/%Y/%m/'),
        ),
    ]
