server {
    listen 80;
    server_name api.lpcrm.yourdomain.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        root /home/lpcrm/lpcrmaws-backend;
    }

    location /media/ {
        root /home/lpcrm/lpcrmaws-backend;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/lpcrm/lpcrmaws-backend/lpcrm.sock;
    }
}
