server {
    listen 80;
    server_name api.lpcrm.yourdomain.com;
    client_max_body_size 50M;

    location = /favicon.ico { access_log off; log_not_found off; }


    location / {
        include proxy_params;
        proxy_pass http://unix:/home/lpcrm/lpcrmaws-backend/lpcrm.sock;
    }
}
