# Generated by Django 5.2.4 on 2026-10-08 10:33

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG'), ('FDS', 'FILMAATIC')], db_index=True, default='LP', max_length=10)),
                ('report_type', models.CharField(choices=[('MORNING', 'Morning Agenda'), ('EVENING', 'Evening Report')], db_index=True, default='EVENING', max_length=20)),
                ('report_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('agenda_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('next_day_agenda', models.TextField(blank=True, null=True)),
                ('name', models.CharField(help_text='Give a title to your daily report', max_length=200, verbose_name='Report Name')),
                ('report_heading', models.CharField(blank=True, help_text='Brief summary of your daily report', max_length=300, null=True, verbose_name='Report Heading')),
                ('agenda_heading', models.CharField(blank=True, help_text='Brief summary of your agenda', max_length=300, null=True, verbose_name='Agenda Heading')),
                ('report_text', models.TextField(blank=True, help_text='Share your daily progress and updates', null=True, verbose_name='Daily Update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('agenda_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('report_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('review_comment', models.TextField(blank=True)),
                ('agenda_review_comment', models.TextField(blank=True)),
                ('report_review_comment', models.TextField(blank=True)),
                ('applied_penalties', models.ManyToManyField(blank=True, related_name='daily_reports', to='hr.penalty')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='reports/attachments/', verbose_name='attached_file')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.dailyreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTimingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_policy', models.CharField(choices=[('EVENING_BEFORE', 'Evening Before'), ('MORNING_OF', 'Morning Of')], default='MORNING_OF', max_length=20)),
                ('agenda_deadline', models.TimeField(default=datetime.time(10, 0))),
                ('report_deadline', models.TimeField(default=datetime.time(18, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
