# Generated by Django 5.2.4 on 2026-05-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_dailyreport_next_day_agenda_dailyreport_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='company',
            field=models.CharField(choices=[('LP', 'LP'), ('FLAG', 'FLAG')], db_index=True, default='LP', max_length=10),
        ),
    ]
