# Generated by Django 5.2.4 on 2026-06-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_dailyreport_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportattachment',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='daily_reports/attachments/'),
        ),
    ]
