# Generated by Django 5.2.4 on 2026-06-09 09:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_dailyreportattachment_attached_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='submission_time',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='agenda_heading',
            field=models.CharField(blank=True, help_text='Brief summary of your agenda', max_length=300, null=True, verbose_name='Agenda Heading'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='agenda_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='report_heading',
            field=models.CharField(blank=True, help_text='Brief summary of your daily report', max_length=300, null=True, verbose_name='Report Heading'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='report_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='report_text',
            field=models.TextField(blank=True, help_text='Share your daily progress and updates', null=True, verbose_name='Daily Update'),
        ),
        migrations.CreateModel(
            name='ReportTimingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_policy', models.CharField(choices=[('EVENING_BEFORE', 'Evening Before'), ('MORNING_OF', 'Morning Of')], default='MORNING_OF', max_length=20)),
                ('agenda_deadline', models.TimeField(default=datetime.time(10, 0))),
                ('report_deadline', models.TimeField(default=datetime.time(18, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
