# Generated by Django 5.2.4 on 2026-06-11 07:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_dailyreport_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportattachment',
            name='attached_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attached_file'),
        ),
    ]
