# Generated by Django 5.2.4 on 2026-06-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_dailyreportattachment_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportattachment',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='attached_file'),
        ),
    ]
