# Generated by Django 5.2.4 on 2026-10-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_penaltytype_penalty_source_report_id'),
        ('reports', '0013_alter_dailyreport_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='agenda_review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='agenda_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='applied_penalties',
            field=models.ManyToManyField(blank=True, related_name='daily_reports', to='hr.penalty'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='report_review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='report_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
