# Generated by Django 5.2.4 on 2026-07-02 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requires_attention_from',
            field=models.ForeignKey(blank=True, help_text='User who needs to reply to the latest query', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_needing_attention', to=settings.AUTH_USER_MODEL),
        ),
    ]
