# Generated by Django 5.2.4 on 2026-08-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
