# Generated by Django 5.2.4 on 2026-10-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_draft_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
