# Generated by Django 5.2.4 on 2026-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoxbayAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, help_text='Full phone number as sent by Voxbay, e.g. 918089040107', max_length=30, unique=True)),
                ('extension', models.CharField(blank=True, help_text='Ext No. from Voxbay, e.g. 513', max_length=20, null=True)),
                ('did_number', models.CharField(blank=True, help_text='DID No. from Voxbay, e.g. 914847173519', max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoxbayDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('report_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VoxbayCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_uuid', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('call_type', models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10, null=True)),
                ('called_number', models.CharField(blank=True, max_length=30, null=True)),
                ('caller_number', models.CharField(blank=True, max_length=30, null=True)),
                ('agent_number', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=30, null=True)),
                ('caller_id', models.CharField(blank=True, max_length=30, null=True)),
                ('call_status', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('conversation_duration', models.IntegerField(blank=True, null=True)),
                ('recording_url', models.TextField(blank=True, null=True)),
                ('call_start', models.DateTimeField(blank=True, null=True)),
                ('call_end', models.DateTimeField(blank=True, null=True)),
                ('dtmf', models.CharField(blank=True, max_length=100, null=True)),
                ('transferred_number', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['call_status'], name='telephony_v_call_st_dc4e18_idx'), models.Index(fields=['call_type'], name='telephony_v_call_ty_4f38e7_idx'), models.Index(fields=['created_at'], name='telephony_v_created_b1afb7_idx')],
            },
        ),
    ]
